server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create