server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qingdao_shipping_service
    username: root
    password: 135555
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update